# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, default='logo.jpg', upload_to='profile_pic')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializations.specialization')),
            ],
        ),
    ]
