# Generated by Django 4.2.7 on 2023-12-08 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_alter_appointment_doctor"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
